### ISSUE TITLE
No longer works in Next.js 14?

### ISSUE THREAD

**Issue by oelbaga** [cedricdelpoux/react-responsive-masonry#125]
This package doesn't seem to work with the most recent Next JS 14 version even in a client component. Just loading the default code brings up these errors in the console:

```
Internal error: ReferenceError: window is not defined
    at useWindowWidth (../node_modules/react-responsive-masonry/es/ResponsiveMasonry/index.js:28:68)
    at MasonryResponsive (../node_modules/react-responsive-masonry/es/ResponsiveMasonry/index.js:60:21)
```

**Comment by cedricdelpoux** [comment]
Can you checkout v`2.3.0`? It should resolve the issue
