### ISSUE TITLE
I ahve Fatching this Error Run In Local Properly but can't when Build My Code I have Use In nextJs Page Routes Can My help Urgenty Thanks Regarsds...   

### ISSUE THREAD

**Issue by Par-biren** [cedricdelpoux/react-responsive-masonry#130]
**info  - Collecting page data ...TypeError: Cannot set property ResponsiveMasonry of #<Object> which has only a getter**
    at Object.<anonymous> (C:\Work\dalle_explore\node_modules\react-responsive-masonry\lib\index.js:18:27)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at 9242 (C:\Work\dalle_explore\.next\server\pages\dall\ai-art-generator.js:2164:18)
    at __webpack_require__ (C:\Work\dalle_explore\.next\server\webpack-runtime.js:25:42)
    at C:\Work\dalle_explore\.next\server\pages\dall\ai-art-generator.js:261:82

**Comment by logan-anderson** [comment]
Getting the same error in nextjs when following the docs.
